- name: DBAL | Checkout master
  shell: cd /vagrant; git clone https://github.com/jackalope/jackalope-doctrine-dbal.git doctrine-dbal creates=/vagrant/doctrine-dbal

- name: DBAL | install dependencies
  shell: cd /vagrant/doctrine-dbal; composer install

- name: DBAL | copy cli-config.php
  copy: src=cli-config-dbal.php dest=/vagrant/doctrine-dbal/cli-config.php

- name: DBAL | remove sqlite database (start fresh)
  shell: rm -f /vagrant/doctrine-dbal/phpcr.sqlite

- name: DBAL | init database
  shell: chdir=/vagrant/doctrine-dbal bin/jackalope jackalope:init:dbal

