---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant
    sys_packages: ["vim","git"]
    php_packages: ["php5-cli","php5-curl","php5-mcrypt","php5-sqlite"]
    php_ppa: php5-oldstable
  roles:
    - init
    - nginx
    - php5-fpm
    - composer
    - phpcommon
    - phpunit
    - jackalope
